name: Create plugin ZIP file

# on:
#   release:
#     types:
#       - created

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Install production dependencies and publish zip
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set version number
      run: |
        sed -i 's/Stable tag: .\+/Stable tag: ${{ github.ref }}/g' readme.txt
        sed -i 's/ * Version: .\+/Version: ${{ github.ref }}/g' two-factor-notakey.php

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install dependencies
      run: |
        composer install -o -q --no-dev

    - name: Zip Folder
      run: zip -r ${{ github.event.repository.name }}.zip . -x ".git/*" ".github/*" ".vscode/*" ".devcontainer/*" "composer.json" "composer.lock" ".gitignore" "README.md" "SECURITY.md"

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}

    - name: Upload zip to release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ github.event.repository.name }}.zip
        asset_name: ${{ github.event.repository.name }}.zip
        asset_content_type: application/zip